name: lint
on: [push]
jobs:
  linter_name:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint using isort
        uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt requirements-test.txt"
      - name: lint using black
        uses: rickstaa/action-black@v1.1.7
        id: action_black
        with:
          black_args: "."
      - name: annotate # TODO(colourdelete): check if we need the `if:`
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
