name: lint
on: [push]
jobs:
  linter_name:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fmt
        run: make fmt
      - name: diff
        id: diff
        run: echo "::set-output name=changes::$(git diff --stages | wc -l)"
      - name: annotate
        if: ${{ steps.diff.changes != 0 }}
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
