name: lint
on: [ push ]
jobs:
  linter_name:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Format
        run: make fmt-setup fmt
      - name: Diff
        id: diff
        run: |
          git add *
          export CHANGES=$(git diff --cached | wc -l)
          echo $CHANGES
      - name: Changes Required
        if: env.CHANGES == 0
        run: |
          echo ${{ toJSON(env) }}
          git diff --cached
          exit 1
